request: development <- 57 fix minor issues annotations
Cusatelli/Case-Se-Java-MeFit pull request #59
Opened 2022-03-11 17:38 UTC by Cusatelli

2022-03-11 17:41 UTC, Cusatelli commented
# ⚠️ Please do not merge before everyone has reviewed this pull-request.

2022-03-14 07:32 UTC, Cusatelli reviewed
I can not find anything at this time, though that might be because I am biased.

2022-03-14 07:32 UTC, Cusatelli commented on src/main/java/com/noroff/mefit/security/SecurityConfig.java
> +                        .antMatchers("/swagger-ui", "/swagger-ui/*", "/swagger-ui/**").permitAll()
Database or KeyCloak public access points?

2022-03-14 07:32 UTC, Cusatelli commented on src/main/java/com/noroff/mefit/security/SecurityConfig.java
> +                        .antMatchers("/security/admin").hasAnyRole("MeFit_Admin")
Do we need to add all users here manually?

2022-03-14 08:26 UTC, OmarAbdiAli requested changes
schema.sql has a drop if exists thats not working as expected.

2022-03-14 09:38 UTC, OmarAbdiAli approved these changes
Great, its Done!

2022-03-14 09:38 UTC, merged